### ISSUE TITLE
Визуальная составляющая игры

### ISSUE THREAD

**Issue by Pavyk96** [Pavyk96/designer#1]
**Создать дизайнеру**

1. Карту мира игры
2. Карточки действий

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/6a565fef-c2ae-45c2-9229-5cbd51697927)
![Image](https://github.com/Pavyk96/designer/assets/97442666/57878510-6b38-422a-9705-ea379fe2534c)

**Comment by Pavyk96** [comment]
Очень клево
