### ISSUE TITLE
Работа дизайнера по первой главе + базовые спрайты

### ISSUE THREAD

**Issue by Pavyk96** [Pavyk96/designer#2]
- Нарисовать спрайты для первой сцены
- Сделать рубашку карты действий
- Сделать главного героя

_дедлайн 3.11_

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/49a785af-72cf-431b-a2ab-dfad37d1418b)
![Image](https://github.com/Pavyk96/designer/assets/97442666/401d69d7-b2c0-47c4-8069-6a69fad5089c)

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/633f24db-db6d-4c9a-8239-d1b358b4a98f)
![Image](https://github.com/Pavyk96/designer/assets/97442666/70fae36a-69ee-4851-9af9-af297a8f16f4)

**Comment by Pavyk96** [comment]
а нельзя чувака, чуть-чуть по шире сделать?

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/e2339405-99ff-403b-95ca-aee7b762a25b)
![Image](https://github.com/Pavyk96/designer/assets/97442666/9164bbc1-612a-4fd6-bcbe-c4748abb1b2a)

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/0c59d5e1-536c-42f7-bec2-e43b806610f8)
![Image](https://github.com/Pavyk96/designer/assets/97442666/1ec8903c-d0e5-4db1-a932-48d816fa4176)

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/0e141d10-53c3-4214-9520-122c211116c5)

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/54d1c76a-a76f-4d29-ae54-6d077593ba8e)
![Image](https://github.com/Pavyk96/designer/assets/97442666/5fee864e-4407-4b5b-b991-873437bc9686)
![Image](https://github.com/Pavyk96/designer/assets/97442666/40271d51-5364-4829-b9e9-e420a7a8f8e6)

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/d94b4a3e-08c8-4983-964e-699fd7c3c13e)
![Image](https://github.com/Pavyk96/designer/assets/97442666/f0c95a08-f206-4619-824c-c40ddf6f49fe)

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/5ef1d982-1bb4-4c3b-a4fb-dc72acf3ec76)
![Image](https://github.com/Pavyk96/designer/assets/97442666/e48124a3-9871-49e5-9990-c4a7a84ed4ca)
![Image](https://github.com/Pavyk96/designer/assets/97442666/d0fb2881-f0d5-4891-969c-0a6b1d804694)
![Image](https://github.com/Pavyk96/designer/assets/97442666/576f049c-1073-49c9-9bf3-2819a12ccadd)
![Image](https://github.com/Pavyk96/designer/assets/97442666/ebb6cac9-d21a-44e3-b9ec-55bd6e38f5b3)
![Image](https://github.com/Pavyk96/designer/assets/97442666/5ed586c9-5399-48c8-bb71-e50bce922f4a)
![Image](https://github.com/Pavyk96/designer/assets/97442666/304c27e0-7cdc-4a9a-8e1c-be52300e8265)
![Image](https://github.com/Pavyk96/designer/assets/97442666/ce2331d6-08da-4493-b77f-8e580028a400)

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/416e67e8-ed67-41cf-bcc6-211c2ce13306)
![Image](https://github.com/Pavyk96/designer/assets/97442666/23f60b2f-2d3e-4fc7-bc15-86375e6a0ca1)
![Image](https://github.com/Pavyk96/designer/assets/97442666/7a73e475-81be-49a1-b8fe-ec9cfaffc9d3)
