### ISSUE TITLE
Спрайты для ПРЕДИСЛОВИЯ

### ISSUE THREAD

**Issue by Pavyk96** [Pavyk96/designer#3]
**Сделать спрайты в пиксельном стиле для ПРЕДИСЛОВИЯ**

- Комната Васи
- Вася удивлен
- Перемещение (желательно гифка)

_дедлайн до 12 ноября_

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/90abc563-5995-452a-9096-09cfbd353c15)
