### ISSUE TITLE
Спрайты для Глава 2

### ISSUE THREAD

**Issue by Pavyk96** [Pavyk96/designer#5]
1) Бекграунд
2) Персонажи
3) Карты действий

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/5542d4b1-16c6-42c9-8666-2e111f8e3f91)

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/e289a46a-3b68-46ca-815f-f7f65eb2cf81)

**Comment by Pavyk96** [comment]
очень круто

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/ccc2646b-2b53-4163-bf5b-d78267fb3174)
![Image](https://github.com/Pavyk96/designer/assets/97442666/12356c0d-2efc-4562-a6f4-55623b6a058c)

**Comment by Ledenit** [comment]
![Image](https://github.com/Pavyk96/designer/assets/97442666/34fddf38-7260-4794-8e55-9c6506355d5b)
![Image](https://github.com/Pavyk96/designer/assets/97442666/9c594ce6-ab05-48fb-bbbb-0c92d4907f40)
![Image](https://github.com/Pavyk96/designer/assets/97442666/c1b4d296-de39-44de-beb2-fb04c3061e76)
